### ISSUE TITLE
Task: Setup maven build for building .tar.gz distribution, running unit tests, building docker image and running integration tests

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar-sql#3]
### pom.xml

Instead of copy pasting the apache/pulsar pom.xml, we could reference it as a  parent pom in the pulsar-sql build. That way all dependencyManagement could be reused without redefining everything. 

### integration tests

The tests could reference the `org.apache.pulsar.tests:integration` library that is already available in Maven Central. 

### docker image

For the docker image, `apachepulsar/pulsar-sql`, it could use the existing `apachepulsar/pulsar` image as the base image. If there's a need for `apachepulsar/pulsar-sql-all`, it could be based on `apachepulsar/pulsar-all`.

We should use the 4.0 LTS version as the parent pom and parent image. Pulsar 4.0.0 will be released by October 25th, 2024.

**Comment by nodece** [comment]
I tried to use the apache/pulsar pom.xml as the parent pom, and then extends uses all plugins and dependencies, I found some plugins cannot work. For example, the plugin cannot find some files(this file exits on apache/pulsar).

Do you have any idea? I want to copy the apache/pulsar pom.xml as the apach/pulsar-sql/pulsar-sql/pom.xml.

**Comment by lhotari** [comment]
> I tried to use the apache/pulsar pom.xml as the parent pom, and then extends uses all plugins and dependencies, I found some plugins cannot work. For example, the plugin cannot find some files(this file exits on apache/pulsar).
> 
> Do you have any idea? I want to copy the apache/pulsar pom.xml as the apach/pulsar-sql/pulsar-sql/pom.xml.
> 

Please share your WIP and steps to reproduce. We'd like to avoid copy-pasting as much as possible to reduce further maintenance overhead.

**Comment by nodece** [comment]
Thank @lhotari, I submitted https://github.com/apache/pulsar-sql/pull/6 for build .tar.gz distribution, it works fine.

## Task
- [x] Building .tar.gz distribution
- [ ] Running unit test in the CI
- [ ] Building docker image and running integration tests
